#!/bin/bash -l
# ./sbatch-af2genomics ligands | sbatch
# date; time snakemake --profile smk-simple-slurm-eu --snakefile workflow/Snakefile-ligands.smk --rerun-triggers input
LOGS_DATE=logs/`date +"%y-%m-%d"`
JOBNAME=sbatch-af2genomics:$1
cat - <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=$JOBNAME
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=2G
#SBATCH --time=3-00:00:00
#SBATCH --output=$LOGS_DATE/$JOBNAME-%j.txt
source /cluster/home/jjaenes/.bashrc
module load eth_proxy
conda activate af2genomics-envA
date; time snakemake --profile smk-simple-slurm-eu --unlock
date; time snakemake --profile smk-simple-slurm-eu --snakefile workflow/Snakefile-$1.smk --rerun-triggers input
myjobs -j \$SLURM_JOB_ID
EOF